### ISSUE TITLE
Can't specify CODEOWNERS file in root of workspace

### ISSUE THREAD

**Issue by ashleyw** [HCoban/codeowners#1]
Looks like you can't specify a CODEOWNERS file in the root of the workspace using `extension.codeOwnersPath`?

Thanks!

**Comment by HCoban** [comment]
@ashleyw Apologies for the delayed response. `extension.codeOwnersPath` expects a full path of the folder where CODEOWNERS file is located. By default, the CODEOWNERS file is looked for in the `.github/` folder. 

Could you please describe the issue you are facing? If your CODEOWNERS file is not in `.github/` directory but just in the root folder, you'll need to assign the full path of the project root, like `/Users/myUserName/Documents/projects/myProject`,  to `extension.codeOwnersPath`. Please let me know if you are still facing the issue.

**Comment by HCoban** [comment]
If you would like to have the codeowners file named different than CODEOWNERS, this is not supported but I can definitely add that feature.
